# -*- coding: utf-8 -*-
"""UTS-NLP-NURFIRA-RAMADAN-20230420500043

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194_de2jHIyoVv9EWxzGYkQX-zVJj8efJ
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Ganti nama file sesuai file kamu
df = pd.read_csv('Ganjil.csv')

# Lihat data
df.head()

"""1. Text Cleaning (Pembersihan Teks)"""

import re

def clean_text(text):
    text = str(text)
    text = re.sub(r'http\S+', '', text)  # hapus URL
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # hapus angka & simbol
    text = re.sub(r'\s+', ' ', text).strip()  # hapus spasi berlebih
    return text

# Fix for the KeyError: 'Berita' due to incorrect CSV parsing
# If 'No;Berita' column exists, extract the 'Berita' part.
if 'No;Berita' in df.columns:
    # Use str.partition to safely get the part after the first semicolon
    # The partition method returns a DataFrame, so we access the third column directly by index [2]
    df['Berita_content'] = df['No;Berita'].astype(str).str.partition(';')[2]
    df['cleaning'] = df['Berita_content'].apply(clean_text)
    df[['Berita_content', 'cleaning']].head()
elif 'Berita' in df.columns:
    # If 'Berita' column already exists (e.g., if the CSV reading was fixed elsewhere),
    # proceed with the original logic.
    df['cleaning'] = df['Berita'].apply(clean_text)
    df[['Berita', 'cleaning']].head()
else:
    # Handle case where neither expected column is found (e.g., different column names)
    print("Error: Neither 'Berita' nor 'No;Berita' column found. Please check your DataFrame columns.")
    print("Available columns:", df.columns.tolist())

import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Pastikan sudah mendownload resource NLTK yang diperlukan
import nltk
nltk.download('punkt')
nltk.download('stopwords')

def clean_text(text):
    # 1. Mengubah teks menjadi lowercase (huruf kecil)
    text = text.lower()

    # 2. Menghapus URL (jika ada)
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # 3. Menghapus karakter spesial, angka, dan emoji
    # Kita hanya menyisakan huruf a-z
    text = re.sub(r'[^a-z\s]', '', text)

    # 4. Menghapus tanda baca (punctuation)
    text = text.translate(str.maketrans('', '', string.punctuation))

    # 5. Tokenisasi (memecah kalimat menjadi kata)
    tokens = word_tokenize(text)

    # 6. Menghapus Stopwords (kata umum yang kurang bermakna seperti 'yang', 'di', 'ke')
    stop_words = set(stopwords.words('indonesian'))
    # Opsional: Tambahkan kata spesifik yang ingin dibuang (misal: 'kompascom')
    additional_stop_words = {'kompascom', 'baca', 'juga'}
    stop_words.update(additional_stop_words)

    filtered_text = [word for word in tokens if word not in stop_words]

    # Menggabungkan kembali menjadi satu string
    return " ".join(filtered_text)

# Input Kalimat
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

cleaned_text = clean_text(raw_text)

print("--- Teks Sebelum Cleaning ---")
print(raw_text)
print("\n--- Teks Sesudah Cleaning ---")
print(cleaned_text)

"""2. TOKENIZATION"""

from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource

df['tokenizing'] = df['cleaning'].apply(word_tokenize)

df[['cleaning', 'tokenizing']].head()

kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
pisah = kalimat.split()
print(pisah)

"""3. NORMALIZATION"""

# contoh kamus sederhana
normalisasi = {
    "gk": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "kpk": "komisi pemberantasan korupsi"
}

def normalize_text(tokens):
    return [normalisasi.get(word, word) for word in tokens]

df['normalization'] = df['tokenizing'].apply(normalize_text)

df[['tokenizing', 'normalization']].head()

import re

def normalize_text(text):
    # Mapping normalisasi: "Kata Tidak Baku/Singkatan": "Kata Baku"
    normalization_dict = {
        "kpk": "komisi pemberantasan korupsi",
        "djbc": "direktorat jenderal bea cukai",
        "plt": "pelaksana tugas",
        "ditjen": "direktorat jenderal",
        "sp3": "surat perintah penghentian penyidikan",
        "kasi": "kepala seksi"
    }

    # 1. Kecilkan huruf terlebih dahulu agar match dengan dictionary
    text = text.lower()

    # 2. Tokenisasi sederhana untuk mencocokkan kata per kata
    words = text.split()

    # 3. Proses penggantian kata
    normalized_words = []
    for word in words:
        # Menghapus tanda baca yang menempel pada kata (misal: "djbc.")
        clean_word = word.strip(string.punctuation)

        if clean_word in normalization_dict:
            # Ganti dengan versi panjangnya
            replacement = normalization_dict[clean_word]
            normalized_words.append(replacement)
        else:
            normalized_words.append(word)

    return " ".join(normalized_words)

# Contoh penggunaan dengan teks yang sudah dibersihkan sedikit (atau teks asli)
raw_text = "Plt Direktur Penyidikan KPK mengatakan ada dokumen di kantor DJBC terkait tersangka."

normalized_result = normalize_text(raw_text)

print("--- Sebelum Normalisasi ---")
print(raw_text)
print("\n--- Sesudah Normalisasi ---")
print(normalized_result)

"""4. Stopword Removal"""

from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('indonesian'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['stopword'] = df['normalization'].apply(remove_stopwords)

df[['normalization', 'stopword']].head()

!pip install Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
import re

# 1. Inisialisasi Factory Stopword Sastrawi
factory = StopWordRemoverFactory()
stopword_remover = factory.create_stop_word_remover()

# 2. Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

# 3. Pre-processing sederhana (Lowercasing)
# Stopword removal bekerja lebih baik jika teks sudah dalam huruf kecil
clean_text = raw_text.lower()

# 4. Proses Penghapusan Stopwords
result = stopword_remover.remove(clean_text)

print("--- Teks Setelah Stopword Removal ---")
print(result)

"""5. Case Folding"""

def case_folding(tokens):
    return [word.lower() for word in tokens]

df['casefolding'] = df['stopword'].apply(case_folding)

df[['stopword', 'casefolding']].head()

#import word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize

kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"

tokens = nltk.tokenize.word_tokenize(kalimat)
print(tokens)

from nltk.tokenize import word_tokenize
import string

kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"

kalimat = kalimat.translate(str.maketrans('', '', string.punctuation)).lower()
__builtins__.print(kalimat)

# Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

def case_folding(text):
    # Menggunakan fungsi bawaan Python .lower()
    return text.lower()

# Eksekusi
folded_text = case_folding(raw_text)

print("--- Hasil Case Folding ---")
print(folded_text)

"""6. Stemming"""

!pip install Sastrawi

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

df['stemming'] = df['casefolding'].apply(stemming)

df[['casefolding', 'stemming']].head()

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# 1. Inisialisasi Stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# 2. Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

# 3. Proses Stemming
# Stemmer Sastrawi secara otomatis melakukan lowercase sebelum memproses
stemmed_text = stemmer.stem(raw_text)

print("--- Hasil Stemming ---")
print(stemmed_text)

from nltk.stem import PorterStemmer

ps = PorterStemmer()

kata = ["JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"]

for k in kata:
    print(k, ":", ps.stem(k))

from nltk.stem import PorterStemmer

porter_stemmer = PorterStemmer()

words = ["JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"]

stemmed_words = [porter_stemmer.stem(word) for word in words]

print("Original words:", words)

print("Stemmed words:", stemmed_words)

from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer (language='english')

words_to_stem = ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']

stemmed_words = [stemmer.stem(word) for word in words_to_stem]

print("Original words:", words_to_stem)

print("Stemmed words:", stemmed_words)

from nltk.stem import LancasterStemmer

stemmer = LancasterStemmer()

words_to_stem = ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']

stemmed_words = [stemmer.stem(word) for word in words_to_stem]

print("Original words:", words_to_stem)

print("Stemmed words:", stemmed_words)

"""7. Lemmatization"""

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

def lemmatization(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df['lemmatization'] = df['stemming'].apply(lemmatization)

df[['stemming', 'lemmatization']].head()

from nltk.tokenize import word_tokenize

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
text = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
tokens = word_tokenize(text)

lemmatized_words = [lemmatizer.lemmatize(word) for word in tokens]

print(f"Original Text: {text}")

print(f"Lemmatized Words: {lemmatized_words}")

from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet # Import wordnet for POS tags
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

lemmatizer = WordNetLemmatizer()
sentence = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
tokens = word_tokenize(sentence)
tagged_tokens = pos_tag(tokens)

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return 'a'
    elif tag.startswith('V'):
        return 'v'
    elif tag.startswith('N'):
        return 'n'
    elif tag.startswith('R'):
        return 'r'
    else:
        return 'n'

lemmatized_sentence = []
for word, tag in tagged_tokens:
    lemmatized_sentence.append(lemmatizer.lemmatize(word, get_wordnet_pos(tag)))

print(f"Original Sentence: {sentence}")
print(f"Lemmatized Sentence: {' '.join(lemmatized_sentence)}")

!pip install stanza
import stanza

# 1. Download dan inisialisasi model bahasa Indonesia
stanza.download('id') # Jalankan ini jika pertama kali menggunakan
nlp = stanza.Pipeline('id', processors='tokenize,lemma')

# 2. Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

# 3. Proses Lemmatization
doc = nlp(raw_text)

# 4. Mengambil lemma dari setiap kata
lemmatized_words = [word.lemma for sent in doc.sentences for word in sent.words]

# Menggabungkan kembali menjadi string
lemmatized_text = " ".join(lemmatized_words)

print("--- Hasil Lemmatization (Stanza) ---")
print(lemmatized_text)